<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
    <LangVersion>latest</LangVersion>
    <!--<EnablePackageValidation>true</EnablePackageValidation>-->
    <!--<PackageValidationBaselineVersion>x.x.x</PackageValidationBaselineVersion>-->
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>Pure.Serialization.Json</PackageId>
    <RootNamespace>Pure.Serialization.Json</RootNamespace>
    <AssemblyName>Pure.Serialization.Json</AssemblyName>
    <Authors>Dmitry Kurochkin</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/kudima03/Pure.Serialization.Json</PackageProjectUrl>
  </PropertyGroup>
</Project>
