<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTrimmable>true</IsTrimmable>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <EnableAotAnalyzer>true</EnableAotAnalyzer>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>Pure.Serialization.Json</PackageId>
    <RootNamespace>Pure.Serialization.Json</RootNamespace>
    <AssemblyName>Pure.Serialization.Json</AssemblyName>
    <Authors>Dmitry Kurochkin</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/kudima03/Pure.Serialization.Json</PackageProjectUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.ILLink.Tasks" Version="10.0.4" />
  </ItemGroup>
</Project>
